using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LORModingBase.DLLEditor
{
    class AutoGenerateCodeBlockDataManagement
    {
        /// <summary>
        /// Loaded code block dictionary data (Directory, Title, CodeBlock)
        /// </summary>
        public static List<AutoGenerateCodeBlock> loadedAutoGenCodeBlocks = new List<AutoGenerateCodeBlock>();

        #region Save / Load code block dictionary data
        /// <summary>
        /// Load code block dictionary data
        /// </summary>
        public static void LoadData()
        {
            loadedAutoGenCodeBlocks.Clear();
            if (!Directory.Exists(DS.PROGRAM_PATHS.AUTO_GENERATE_CODE_BLOCK))
                Directory.CreateDirectory(DS.PROGRAM_PATHS.AUTO_GENERATE_CODE_BLOCK);

            Directory.GetFiles(DS.PROGRAM_PATHS.AUTO_GENERATE_CODE_BLOCK).ToList().ForEach((string codeBlockFile) =>
            {
                if (codeBlockFile.Split('.').Last() == "json")
                {
                    Dictionary<string, List<string>> loadedCodeBlockDes = Tools.JsonFile.LoadJsonFile<Dictionary<string,List<string>>>(codeBlockFile);
                    if(loadedCodeBlockDes.ContainsKey(DM.Config.config.localizeOption))
                    {
                        List<string> localizedCodeBlockDes = loadedCodeBlockDes[DM.Config.config.localizeOption];
                        AutoGenerateCodeBlock newAutoGeneratedCodeBlock = new AutoGenerateCodeBlock();
                        newAutoGeneratedCodeBlock.title = localizedCodeBlockDes[0];
                        newAutoGeneratedCodeBlock.description = localizedCodeBlockDes[1];
                        newAutoGeneratedCodeBlock.parameterNameList = localizedCodeBlockDes[2].Split(',').ToList();

                        string SOURCE_DATA = codeBlockFile.Replace(".json", ".txt");
                        if (File.Exists(SOURCE_DATA))
                            newAutoGeneratedCodeBlock.codes = File.ReadAllText(SOURCE_DATA);
                        loadedAutoGenCodeBlocks.Add(newAutoGeneratedCodeBlock);
                    }
                }  
            });
        }
        #endregion
    }
}
